# RBAC used by the webhook
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name }}"
  namespace: {{ .Values.ns }}
  labels:
    {{- include "a-w-nodeselector.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.serviceAccount.name }}"
  namespace: {{ .Values.ns }}
  labels:
    {{- include "a-w-nodeselector.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.serviceAccount.name }}"
  namespace: {{ .Values.ns }}
  labels:
    {{- include "a-w-nodeselector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Values.serviceAccount.name }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.serviceAccount.name }}"
    namespace: {{ .Values.ns }}