name: main

on: 
  push:
    branches:    
      - main
    tags:
      - '*'

env:
  ACR_NAME: tsaktest
  ACR_REPO_NAME: admission-webhook-nodeselector
  ACR_PUSH_USER: tsaktest
  DOCKER_TAG: v1.25.0
  
jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ env.ACR_PUSH_USER }}
        password: ${{ secrets.ACR_PUSH_TOKEN }}
 
    - name: Build the frontend image and push it to ACR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.ACR_NAME }}.azurecr.io/${{ env.ACR_REPO_NAME }}:${{ env.DOCKER_TAG }}
        file: ./Dockerfile
  build:
    name: build and push helm
    needs: docker_build_push_acr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
        name: checkout repo
      
      - name: install helm
        uses: azure/setup-helm@v3
          
      - name: login to acr using helm
        run: |
          helm registry login ${{ env.ACR_NAME }}.azurecr.io --username ${{ env.ACR_PUSH_USER }} --password ${{ secrets.ACR_PUSH_TOKEN }}
          
      - name: build and push helm chart
        run: |
          helm package ./charts/a-w-nodeselector --version ${{ github.ref_name }}
          helm push a-w-nodeselector-${{ github.ref_name }}.tgz oci://${{ env.ACR_NAME }}.azurecr.io/helm/admission-webhook
